name: encrypted_key
description: A Dart CLI for encrypting/decrypting sensitive data in/from ASCII format
version: 1.0.0
homepage: https://github.com/romgrm/encrypted_key

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  args: ^2.3.1
  mason_logger: ^0.2.3
  pub_updater: ^0.2.4
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
executables:
  encrypted_key:
